### ISSUE TITLE
Stacked shulkers in Loader

### ISSUE THREAD

**Issue by Zerons24** [sakura-ryoko/tweakeroo#65]
Can the funktion of "shulker Boxes stack on Ground" be reimplemented?
or is there already an alternative Funktion for that?

**Comment by sakura-ryoko** [comment]
the `tweakEmptyShulkerBoxesStackOnGround` was removed by zly2006 because of the fixes done to how the shulker Boxes Stack code works, and the feature was redundant.
If the `tweakEmptyShulkerBoxesStack` code is working as expected, then `tweakEmptyShulkerBoxesStackOnGround` is not necessary.  This is due to how Vanilla changed the process with how items are calculated to stack as of 1.20.6+.

The `tweakEmptyShulkerBoxesStackOnGround` last existed under 1.20.6 and early 1.21 pre-release builds, and then was removed when the code was causing severe de-sync / item destruction problems.  It was also removed to help mitigate any future problems.

**Comment by Zerons24** [comment]
my problem is, that shulkers also stack in hoppers and tile entetis if they are moved into them by hoppers. stacked shulkers in the shulkerstorrage are fine, but if i need to fill my entire farm with full stacks its to expensiv. I found a fix in som other mod but could it be implemented in the base mod? or did i overlock something?

**Comment by sakura-ryoko** [comment]
You may be looking for the stackable-shulker-fix mod.  In more recent versions of Tweakeroo, I have added the Hopper-fix and quoted this mod; but that code only works in Single Player.  But if you are in Multiplayer; Tweakeroo will not fix this.
I would recommend installing this server side:
https://modrinth.com/mod/stackable-shulkers-fix
